name: Release image on tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup environment variables
        run: |
          echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "DOCKER_REPO=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: timoreymann/${{ env.DOCKER_REPO }}:latest, timoreymann/${{ env.DOCKER_REPO  }}:${{ env.GITHUB_TAG }}
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

