on:
  push:
    branches:
      - master
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.3
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/changelog@6.0.1
            conventional-changelog-conventionalcommits@5.0.0
          branches: |
            [
              main,
              master
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
